### ISSUE TITLE
Support for 11.1.2.4

### ISSUE THREAD

**Issue by jwilton** [agardiner/hfmcmd#24]
Firstly, thank you for such a great utility!
Is it possible to compile this against 11.1.2.4?
(The DLLs have all changed names from what I can see, so expecting this to not be a simple answer!)

Thanks, James

**Comment by nwillemse** [comment]
Hi Adam,

It will be great to have support for 11.1.2.4.  I will be needing it later this year as well.  I have a test instance of 11.1.2.4 up and running.  I can help with testing.  I starting looking at your extract_dll.bat script, but it seems that HFM is quite different in 11.1.2.4.

Now that HFM can run on Linux, we might have to port this utility over to Linux...

Thanks again
Nick

**Comment by agardiner** [comment]
Unfortunately, HFM 11.1.2.4 is a completely rewritten version of HFM using Java. The COM interface that was the API to HFM up to version 11.1.2.3 is not supported __at all__ for 11.1.2.4.
This means that updating HFMCmd to support 11.1.2.4 is simply not possible. HFM 11.1.2.4 would need a completely new, re-written version of HFMCmd in Java. This is a huge undertaking, since apart from the different tooling, the API is not even similar to what was there before.
I might attempt this one day, but it won't be in the immediate future. I am not working with HFM at present, and don't have an 11.1.2.4 instance to work with or the time to put into this.
I am sorry to be the bearer of bad news. I understand Oracle's decision to move HFM to the Java technology stack, but the casualties of this change in architecture are all the utilities and tools that were built using the old API.
